user_name = input("Enter your name")
print(f"Hello, glad to see you {user_name}")
user_email = input("Enter your user_email :")
print(user_email)
user_age = input("Enter your year of birth :")
print(user_age)
